export const BRANDS = [
  {
    id: 'dominos',
    name: "Domino's Pizza",
    logo: null,
    color: '#006491',
    accent: '#E31837',
    emoji: '🍕',
    tag: 'Pizza · Fast Food',
    rating: 4.3,
    time: '25-35 min',
  },
  {
    id: 'kfc',
    name: 'KFC',
    logo: null,
    color: '#F40027',
    accent: '#F9A000',
    emoji: '🍗',
    tag: 'Chicken · Fast Food',
    rating: 4.1,
    time: '20-30 min',
  },
  {
    id: 'burgerman',
    name: 'BurgerMan',
    logo: null,
    color: '#D62300',
    accent: '#FFC72C',
    emoji: '🍔',
    tag: 'Burgers · American',
    rating: 4.4,
    time: '15-25 min',
  },
  {
    id: 'subway',
    name: 'Subway',
    logo: null,
    color: '#008C15',
    accent: '#FFC600',
    emoji: '🥖',
    tag: 'Subs · Healthy',
    rating: 4.0,
    time: '15-20 min',
  },
  {
    id: 'pizzahut',
    name: 'Pizza Hut',
    logo: null,
    color: '#EE3124',
    accent: '#FFC72C',
    emoji: '🍕',
    tag: 'Pizza · Italian',
    rating: 4.2,
    time: '30-40 min',
  },
  {
    id: 'mcdonalds',
    name: "McDonald's",
    logo: null,
    color: '#DA291C',
    accent: '#FFC72C',
    emoji: '🍟',
    tag: 'Burgers · Fast Food',
    rating: 4.0,
    time: '15-25 min',
  },
  {
    id: 'tacobell',
    name: 'Taco Bell',
    logo: null,
    color: '#702082',
    accent: '#F37F00',
    emoji: '🌮',
    tag: 'Mexican · Fast Food',
    rating: 3.9,
    time: '20-30 min',
  },
  {
    id: 'burgerking',
    name: 'Burger King',
    logo: null,
    color: '#D62300',
    accent: '#ECB02C',
    emoji: '👑',
    tag: 'Burgers · Grilled',
    rating: 4.1,
    time: '20-30 min',
  },
];

export const MENU = {
  dominos: [
    { id: 'd1', name: 'Margherita Pizza', price: 199, image: '🍕', available: 15, desc: 'Classic cheese & tomato' },
    { id: 'd2', name: 'Pepperoni Pizza', price: 299, image: '🍕', available: 10, desc: 'Double pepperoni delight' },
    { id: 'd3', name: 'BBQ Chicken Pizza', price: 349, image: '🍕', available: 8, desc: 'Smoky BBQ with chicken' },
    { id: 'd4', name: 'Veggie Paradise', price: 249, image: '🥗', available: 12, desc: 'Fresh garden veggies' },
    { id: 'd5', name: 'Pasta Carbonara', price: 179, image: '🍝', available: 20, desc: 'Creamy white sauce pasta' },
    { id: 'd6', name: 'Choco Lava Cake', price: 89, image: '🎂', available: 25, desc: 'Warm molten chocolate' },
  ],
  kfc: [
    { id: 'k1', name: 'Original Recipe Chicken', price: 249, image: '🍗', available: 20, desc: '11 secret herbs & spices' },
    { id: 'k2', name: 'Zinger Burger', price: 179, image: '🍔', available: 18, desc: 'Spicy crispy fillet' },
    { id: 'k3', name: 'Popcorn Chicken', price: 149, image: '🍿', available: 30, desc: 'Bite-sized crispy chicken' },
    { id: 'k4', name: 'Bucket of 8 Pieces', price: 599, image: '🪣', available: 10, desc: 'Family feast bucket' },
    { id: 'k5', name: 'Coleslaw', price: 59, image: '🥗', available: 50, desc: 'KFC signature coleslaw' },
    { id: 'k6', name: 'Pepsi', price: 49, image: '🥤', available: 100, desc: 'Chilled Pepsi 500ml' },
  ],
  burgerman: [
    { id: 'b1', name: 'Classic Smash Burger', price: 199, image: '🍔', available: 15, desc: 'Double smash patty' },
    { id: 'b2', name: 'BBQ Bacon Burger', price: 249, image: '🍔', available: 12, desc: 'Bacon & BBQ sauce' },
    { id: 'b3', name: 'Truffle Mushroom Burger', price: 279, image: '🍄', available: 8, desc: 'Truffle aioli & mushroom' },
    { id: 'b4', name: 'Crispy Chicken Burger', price: 219, image: '🍗', available: 10, desc: 'Southern fried chicken' },
    { id: 'b5', name: 'Loaded Fries', price: 129, image: '🍟', available: 25, desc: 'Cheese & jalapeño fries' },
    { id: 'b6', name: 'Milkshake', price: 99, image: '🥛', available: 20, desc: 'Thick creamy milkshake' },
  ],
  subway: [
    { id: 's1', name: 'Italian B.M.T', price: 249, image: '🥖', available: 20, desc: 'Ham, pepperoni, salami' },
    { id: 's2', name: 'Veggie Delite', price: 179, image: '🥗', available: 25, desc: 'Fresh garden veggies' },
    { id: 's3', name: 'Chicken Teriyaki', price: 269, image: '🍗', available: 15, desc: 'Teriyaki glazed chicken' },
    { id: 's4', name: 'Tuna Sub', price: 229, image: '🐟', available: 10, desc: 'Classic tuna with mayo' },
    { id: 's5', name: 'Cookies', price: 49, image: '🍪', available: 50, desc: 'Freshly baked cookies' },
    { id: 's6', name: 'Fountain Drink', price: 39, image: '🥤', available: 100, desc: 'Choice of beverage' },
  ],
  pizzahut: [
    { id: 'ph1', name: 'Pan Pizza', price: 279, image: '🍕', available: 15, desc: 'Deep pan, thick crust' },
    { id: 'ph2', name: 'Stuffed Crust Pizza', price: 349, image: '🍕', available: 10, desc: 'Cheese-stuffed golden crust' },
    { id: 'ph3', name: 'Chicken Wings', price: 199, image: '🍗', available: 20, desc: 'Spicy glazed wings' },
    { id: 'ph4', name: 'Garlic Bread', price: 89, image: '🥖', available: 30, desc: 'Buttery garlic bread' },
    { id: 'ph5', name: 'Pasta Arabiata', price: 169, image: '🍝', available: 15, desc: 'Spicy tomato pasta' },
    { id: 'ph6', name: 'Brownie', price: 99, image: '🍫', available: 20, desc: 'Warm chocolate brownie' },
  ],
  mcdonalds: [
    { id: 'm1', name: 'Big Mac', price: 199, image: '🍔', available: 25, desc: 'Two all-beef patties' },
    { id: 'm2', name: 'McChicken', price: 149, image: '🍔', available: 20, desc: 'Crispy chicken sandwich' },
    { id: 'm3', name: 'Fillet-O-Fish', price: 139, image: '🐟', available: 15, desc: 'Crispy fish fillet' },
    { id: 'm4', name: 'French Fries', price: 79, image: '🍟', available: 50, desc: 'Golden crispy fries' },
    { id: 'm5', name: 'McFlurry', price: 89, image: '🍦', available: 30, desc: 'Creamy soft serve' },
    { id: 'm6', name: 'Happy Meal', price: 179, image: '🎁', available: 20, desc: 'Meal + toy for kids' },
  ],
  tacobell: [
    { id: 't1', name: 'Crunchy Taco', price: 99, image: '🌮', available: 30, desc: 'Original crunchy taco' },
    { id: 't2', name: 'Burrito Supreme', price: 179, image: '🌯', available: 20, desc: 'Loaded beef burrito' },
    { id: 't3', name: 'Nachos', price: 129, image: '🧀', available: 25, desc: 'Chips & cheese sauce' },
    { id: 't4', name: 'Quesadilla', price: 149, image: '🫓', available: 15, desc: 'Grilled cheese quesadilla' },
    { id: 't5', name: 'Mexican Pizza', price: 169, image: '🍕', available: 12, desc: 'Taco Bell pizza twist' },
    { id: 't6', name: 'Cinnabon Bites', price: 79, image: '🍩', available: 20, desc: 'Sweet cinnamon bites' },
  ],
  burgerking: [
    { id: 'bk1', name: 'Whopper', price: 229, image: '🍔', available: 20, desc: 'Flame-grilled beef patty' },
    { id: 'bk2', name: 'Chicken Royale', price: 189, image: '🍗', available: 18, desc: 'Crispy chicken fillet' },
    { id: 'bk3', name: 'Onion Rings', price: 89, image: '🧅', available: 25, desc: 'Golden crispy rings' },
    { id: 'bk4', name: 'BK Veggie Burger', price: 149, image: '🌿', available: 15, desc: 'Plant-based patty' },
    { id: 'bk5', name: 'Mozzarella Sticks', price: 119, image: '🧀', available: 20, desc: 'Gooey mozzarella sticks' },
    { id: 'bk6', name: 'Sundae', price: 69, image: '🍨', available: 30, desc: 'Ice cream sundae' },
  ],
};

export const COUPONS = {
  SAVE10: 10,
  TASTY20: 20,
  FEAST15: 15,
  WELCOME30: 30,
};